# Copyright (C) 2014 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: goran@reciprocitylabs.com
# Maintained By: goran@reciprocitylabs.com

---
- name: create development directories
  sudo: yes
  with_items: ggrc_development_directories
  file:
    path: "{{ item.name }}"
    owner: vagrant
    group: vagrant
    state: directory

- name: prepare development virtualenv
  command: make setup_dev DEV_PREFIX=/vagrant-dev
  args:
    chdir: /vagrant

- name: install gems
  sudo: yes
  with_items: ggrc_gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    state: present

- name: install global npm modules
  sudo: yes
  with_items: ggrc_global_npm_modules
  npm:
    name: "{{ item.name }}"
    global: yes
    state: present

- name: run make appengine
  command: make appengine DEV_PREFIX=/vagrant-dev
  args:
    chdir: /vagrant

- name: run make bower_components
  command: make bower_components
  args:
    chdir: /vagrant

- name: configure bash
  sudo: yes
  template:
    src: .bashrc.j2
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
