# Copyright (C) 2014 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: goran@reciprocitylabs.com
# Maintained By: goran@reciprocitylabs.com

---
- name: install gems
  sudo: yes
  with_items: ggrc_gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    state: present

- name: install global npm modules
  sudo: yes
  with_items: ggrc_global_npm_modules
  npm:
    name: "{{ item.name }}"
    global: yes
    state: present

- name: run make bower_components
  command: make bower_components
  args:
    chdir: /vagrant
