version: "2"
services:
  cleandev:
    extends:
      service: cleandev
      file: common-services.yml
    ports:
     - "127.0.0.1:8001:8000"
     - "127.0.0.1:8081:8080"
     - "127.0.0.1:9877:9876"
    depends_on:
      - db
    networks:
      - network_cleandev
      - selenium
  db:
    extends:
      service: db
      file: common-services.yml
    networks:
      - network_cleandev
  selenium:
    build:
      context: .
      dockerfile: Dockerfile-selenium
    volumes:
     - "./test/selenium:/selenium"
     - "/dev/shm:/dev/shm"
    depends_on:
      - cleandev
    networks:
      - selenium
    environment:
     - "TZ=America/Los_Angeles"
     - PYTHONDONTWRITEBYTECODE=true
     - PYTHONPATH=/selenium/src
     - SCREEN_WIDTH=1440
     - SCREEN_HEIGHT=900
networks:
  network_cleandev:
  selenium:
